0: pyxis: importing docker image ...
0: /workspace
0: /home/lmcafee/src/megatrons/megatron-lm-boxin
0: Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
0: Collecting h5py
0:   Downloading h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
0: Requirement already satisfied: numpy>=1.14.5 in /opt/conda/lib/python3.8/site-packages (from h5py) (1.22.3)
0: Installing collected packages: h5py
0: Successfully installed h5py-3.7.0
0: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
0: time / train_data = 0.003352.
0: time / test_data = 0.000001.
0: Traceback (most recent call last):
0:   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
0:     return _run_code(code, main_globals, None,
0:   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
0:     exec(code, run_globals)
0:   File "/home/lmcafee/src/megatrons/megatron-lm-boxin/lawrence/acc/test_index_acc.py", line 441, in <module>
0:     test_knn()
0:   File "/home/lmcafee/src/megatrons/megatron-lm-boxin/lawrence/acc/test_index_acc.py", line 318, in test_knn
0:     pax({
0:   File "/home/lmcafee/src/sandbox/lutil/pax.py", line 218, in pax
0:     raise Exception("pax.")
0: Exception: pax.
0: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
0: [rank None, /home/lmcafee/src/megatrons/megatron-lm-boxin/lawrence/acc/test_index_acc.py:318]
0: TRAIN_DATA = str([9328]; (0, 1024)).
0: TEST_DATA  = str([9392]; (0, 1024)).
0: [rank None, /home/lmcafee/src/megatrons/megatron-lm-boxin/lawrence/acc/test_index_acc.py:318]
0: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
